"""empty message

Revision ID: 65c2b5866d22
Revises: 
Create Date: 2019-09-28 19:38:25.613549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c2b5866d22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asins_amazon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parse_date', sa.Date(), nullable=True),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('sections', sa.String(), nullable=True),
    sa.Column('photos', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_shop_parse_date'), 'items_shop', ['parse_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_shop_parse_date'), table_name='items_shop')
    op.drop_table('items_shop')
    op.drop_table('asins_amazon')
    # ### end Alembic commands ###
